CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullname" VARCHAR(50),
  "email" VARCHAR(60),
  "created_at" TIMESTAMP
);

CREATE TABLE "tickets" (
  "ticket_id" integer PRIMARY KEY,
  "timetable_id" integer,
  "user_id" integer,
  "row" integer,
  "seat" integer,
  "fullcost" real,
  "cost" real,
  "discount_id" integer,
  "seat_type" integer,
  "created_at" datetime
);

CREATE TABLE "halls" (
  "hall_id" integer PRIMARY KEY,
  "name" varchar(50),
  "type" varchar(50),
  "number_seats" integer,
  "low_category" integer,
  "vip_category" integer
);

CREATE TABLE "timetable" (
  "timetable_id" integer PRIMARY KEY,
  "hall_id" integer,
  "movie_id" integer,
  "start_time" timestamp,
  "duration_minute" integer,
  "low_seat_price" numeric,
  "vip_seat_price" numeric,
  "created_at" timestamp
);

CREATE TABLE "movies" (
  "movie_id" integer PRIMARY KEY,
  "title" varchar(60),
  "rating" real,
  "duration_minute" real,
  "imdb_id" int
);

ALTER TABLE "tickets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "tickets" ADD FOREIGN KEY ("timetable_id") REFERENCES "timetable" ("timetable_id");

ALTER TABLE "timetable" ADD FOREIGN KEY ("hall_id") REFERENCES "halls" ("hall_id");

ALTER TABLE "timetable" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("movie_id");
