customerID(M: 1) employeeID
customerID(1: M) orders.orderIDD
orderID(1: 1) customerID
orderID(M: 1) employeeID
orderDetails.orderDetailID(1: M) orderID
orderDetailID(1: M) products.productID
productID(M: 1) categoryID
shipperID(1: M) orders.orderID
suppliers.supplierID(1: M) products.productID