CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp,
  "full_name" varchar,
  "email" varchar,
  "password" varchar(hash)
);

CREATE TABLE "tracks" (
  "track_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp,
  "title" varchar,
  "duration_sec" int,
  "album_id" int,
  "artist_id" int,
  "file_url" varchar
);

CREATE TABLE "albums" (
  "album_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp,
  "title" varchar,
  "artist_id" int,
  "release_date" timestamp,
  "poster_url" varchar
);

CREATE TABLE "artists" (
  "artist_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp,
  "full_name" varchar
);

CREATE TABLE "playlists" (
  "playlist_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp,
  "title" varchar,
  "user_id" int,
  "track_id" int
);

ALTER TABLE "tracks" ADD FOREIGN KEY ("album_id") REFERENCES "albums" ("album_id");

ALTER TABLE "tracks" ADD FOREIGN KEY ("artist_id") REFERENCES "artists" ("artist_id");

ALTER TABLE "albums" ADD FOREIGN KEY ("artist_id") REFERENCES "artists" ("artist_id");

ALTER TABLE "playlists" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "tracks" ADD FOREIGN KEY ("track_id") REFERENCES "playlists" ("track_id");
